### ISSUE TITLE
Doesn't seem to work on macOS High Sierra?

### ISSUE THREAD

**Issue by olliejm** [newmarcel/KeepingYouAwake#92] opened 2017-09-30 14:58 UTC
I just upgraded to High Sierra and I've noticed that my Mac sleeps as normal regardless of whether or not I have KeepingYouAwake enabled. Is this a known issue? If there's any extra info I can provide let me know.

**Comment by chapter09** [comment] 2017-10-03 13:44
I have the same problem. The KeepingYouAwake does not work on High Sierra.

**Comment by vmfhrmfoaj** [comment] 2017-10-05 10:16
If you enable 'Deactivate when battery is below' option in the 'Advance' tab, turn off the option.
In my case, it's works.

**Comment by johnmmcgee** [comment] 2017-10-08 21:46
This did not fix the issue.  It seems none of the prevent sleep programs work any longer on High Sierra.

**Comment by alexandreleroux** [comment] 2017-10-10 00:59
KYA 1.4.2 (1040204) appears to work fine with me on macOS 10.13.0 on my iMac. Seems like not everyone has issues?

**Comment by ottodevs** [comment] 2017-10-12 15:36
macOS 10.13 here, KYA 1040204 not working with or without the 'Deactivate when battery is below' option ticked...

So it seems the problem is some kind of incompatibility between KYA and High Sierra.

Let's check if caffeinate terminal command is working to locate if the origin of the problem is there

**Comment by newmarcel** [comment] 2017-10-21 10:04
Thanks for reporting and thanks for trying to narrow it down. I have updated all my machines to High Sierra and didn't run into the mentioned issues yet.

If you run into this again, could you please provide some more details?
- was it enabled with timeout or indefinitely?
- do you use "Activate on Launch"?
- do you have any advanced preferences enabled?
- does "Activity Monitor.app" show an entry for `caffeinate`?

These details would help to reproduce the issues.

**Comment by x74353** [comment] 2017-10-24 15:17
Hi, I'm the developer of Amphetamine, and I am experiencing some issues of my own with both Amphetamine and the built-in caffeinate command line utility. 1 of my 3 Macs appears to be completely ignoring applied power assertions. While Amphetamine does not use the caffeinate utility directly, it applies the same PreventUserIdleDisplaySleep assertion that the caffeinate -d command does.  I've only received a handful of reports from Amphetamine users, so I do not think the issue is too widespread.

While I haven't had much time lately to really work on narrowing down the issue, I can say that the Mac that is experiencing the issue is the newest 12-inch MacBook (2017).

My two older Macs, which are a MacBook Pro (Mid-2015, I believe) and a MacBook Pro (15-inch, Late 2016) are not having any issues as far as I can tell. 

I submitted bug reports with Apple a couple weeks ago about this issue, but haven't heard back yet.

**Comment by x74353** [comment] 2017-10-24 15:39
Update - resetting the SMC on my 12-inch MacBook seems to have solved the issue thus far.
https://support.apple.com/en-us/HT201295

**Comment by newmarcel** [comment] 2017-10-25 07:57
@x74353 Wow. If more affected people can confirm that this will fix the issue, I'll have to think about adding some kind of Help link to the app until this is fixed.
I still haven't experienced these issues on any of my machines.

**Comment by levthedev** [comment] 2017-10-25 15:19
@newmarcel 
I have this issue too. For me, resetting the SMC fixed the issue until I checked the "disable when below certain battery" button. But now, even unchecking that button does not fix it.

For reference, I have a mid 2014 Macbook Pro. KYA has this indefinite time, launch at login, and the disable beneath battery level unchecked.

Also, if it helps, I didn't seem to have this issue when I was using Caffeinate or InsomniaX. I switched to KYA because it has the setting for disabling beneath battery, but now not only is that broken, but the basic functionality of disabling at all is broken.

Would love any updates to this issue - I've subscribed to this thread. Thanks for all the hard work! 😃

**Comment by levthedev** [comment] 2017-10-25 15:24
Also, @x74353 - I have the same problem with your app. Even after resetting my SMC, it doesn't let me disable sleep. Or rather, it lets me, but unplugging my charger with an external monitor plugged in puts my laptop to sleep.

**Comment by transiti0nary** [comment] 2017-10-31 15:37
I'm still running into this issue. Following setup:

- enabled indefinitely
- not activated on launch
- no advanced prefs enabled
- activity monitor shows an entry for caffeinate

Latest macOS High Sierra (10.13 17A405) and KYA 1.4.2

**Comment by x74353** [comment] 2017-10-31 17:33
@transiti0nary - does the built-in `caffeinate` utility work for you? Try this:

- Open Terminal.app from /Applications/Utilities
- In a new Terminal window type `caffeinate -d`
- Wait for however long your sleep timer is set for to see if your Mac and/or its display sleeps (see the _System Preferences > Energy Saver > Turn display off after:_ setting for how long to wait)

If you Mac falls asleep with the built-in `caffeinate` utility, then something is going on with your Mac, be it a bug in the OS, or an issue with the SMC. Try resetting your SMC again (see linked instructions in my prior post). Triple check you are following the correct instructions for your specific type of Mac.

**Comment by dankegel** [comment] 2017-11-08 02:36
I'm running into this.  Hardware: three Mac Pro's.  OS: 10.13.  Buildslaves, so unattended, but have mouse, keyboard, and display.  Set to not sleep six ways from sunday.  Invoke test runner with
```caffeinate -s -u -i -t 72000 foo.sh``` (tried with many fewer options, too; no combination seems to suffice).

Wait.  Notice test runner has hung while trying to run an opengl test that needs the display.

ssh to machine, look around a bit:

```
$ pmset -g assertionslog
2017-11-07 15:57:23 -0800 : Showing all currently held IOKit power assertions
Assertion status system-wide:
BackgroundTask 0
ApplePushServiceTask 0
UserIsActive 1
PreventUserIdleDisplaySleep 0
PreventSystemSleep 1
ExternalMedia 0
PreventUserIdleSystemSleep 1
NetworkClientActive 1
Listed by owning process:
pid 366(caffeinate): [0x00000025000180ba] 03:16:41 PreventUserIdleSystemSleep named: "caffeinate command-line tool"
Details: caffeinate asserting on behalf of 'sh' (pid 365)
Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
Timeout will fire in 60198 secs Action=TimeoutActionRelease
pid 366(caffeinate): [0x00000025000780bc] 03:16:41 PreventSystemSleep named: "caffeinate command-line tool"
Details: caffeinate asserting on behalf of 'sh' (pid 365)
Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
Timeout will fire in 60198 secs Action=TimeoutActionRelease
pid 366(caffeinate): [0x00000025000980bd] 03:16:41 UserIsActive named: "caffeinate command-line tool"
Details: caffeinate asserting on behalf of 'sh' (pid 365)
Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
Timeout will fire in 60198 secs Action=TimeoutActionRelease
pid 52(powerd): [0x00002cd400118202] 00:06:01 NetworkClientActive named: "com.apple.powermanagement.ttyassertion"
Kernel Assertions: 0x104=USB,MAGICWAKE
id=501 level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.1d100000 owner=Dell USB Entry Keyboard
id=502 level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.1a200000 owner=USB Optical Mouse
id=503 level=255 0x100=MAGICWAKE mod=12/31/69, 4:00 PM description=en0 owner=en0

Showing assertion changes(Press Ctrl-T to log all currently held assertions):
load: 1.22 cmd: pmset 3039 running 0.01u 0.00s
Time Action Type PID(Causing PID) ID Name
==== ====== ==== ================ == ====
```


Walk over and wiggled the mouse / pressed the shift key, and voila, the test woke up, and pmset continued, saying

```
11/07 15:57:59 Created UserIsActive 93 0x2e620009820e com.apple.iohideventsystem.queue.tickle.4294968090.3
```

This has happened on at least two of the Mac Pro's.  For completeness, all three have same model, boot rom version, and smc version:
```
$ system_profiler SPHardwareDataType
Hardware:
    Hardware Overview:
      Model Name: Mac Pro
      Model Identifier: MacPro5,1
      Processor Name: Quad-Core Intel Xeon
      Processor Speed: 2.4 GHz
      Number of Processors: 2
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache (per Processor): 12 MB
      Memory: 6 GB
      Processor Interconnect Speed: 5.86 GT/s
      Boot ROM Version: MP51.0084.B00
      SMC Version (system): 1.39f11
      SMC Version (processor tray): 1.39f11
```
and https://support.apple.com/en-us/HT201518 has no updates.

This appears to be quite repeatable.

OK, trying SMC reset.  https://support.apple.com/en-us/HT201295 indicates that's
essentially a very cold boot, so for each of the 3 machines, I shut down, pulled power cord, pressed power button to get it to drain the caps, waited 2 minutes, plugged in power cord, and turned back on.

When they boot, they start the test runner, which just sits there waiting for jobs... started via caffeine.

On all three, I then logged in via ssh and ran ```pmset -g assertionslog``` and watched,
fiddled with keyboard and mouse a bit, waited to see if their screens would blank (hmm, System Settings / Energy Saver shows the display one two was set to sleep after 2 minutes), and then triggered an 8 minute build that hung today before the reset.

Result: 1 of the three machines hung during the build.  The one with no keyboard or mouse.  Hmm.

On the two that didn't hang, I started a build again, this time not fiddling with them at all first.
I noted that the screen slept on both about 1 minute after boot and autologin.

Result: 1 of the 2 machines hung during the build.

I started a build again on the remaining machine, again not fiddling with it at all.

Result: the remaining machine hung during the build.

Pressed the shift key on one machine.  Result: it woke up and finished the build.

Next, I went into Energy Saver and set all three machines to never sleep the display or
disk.

Repeated build test.  None of the three systems hung this time, no thanks to caffeinate.

Sorry that was so long.  Let me know if you want me to run any other tests.  I see one of
my machines is on a beta channel and has osx 10.13.1 beta on tap, maybe I'll let that load
and see whether it helps.

**Comment by dankegel** [comment] 2017-11-14 22:50
Figured my problem out, I think.  To diagnose it, I wrote the tiny script show.sh, containing
```
#!/bin/sh
set -ex
while sleep 5
do
  ioreg -n IODisplayWrangler | grep -i IOPowerManagement
  ps augxw | grep caffein | grep -v grep
done
```
then ran it with
```
$ caffeinate -d -s -u -i -t 500 sh show.sh
```

This demonstrated that the display slept quite quickly despite the caffeinate.

Looking harder at the man page, -t is for *this assertion*, and has to be repeated for each assertion, e.g.
```
$ caffeinate -d -t 500 -s -t 500 -ut 500 -i -t 500 sh show.sh
```
I think that solves my particular problem.

Sorry for the noise.

**Comment by dankegel** [comment] 2017-11-21 03:39
Caught it misbehaving again.

Symptom: test that uses the display hangs.
While the hang is in progress, I ssh into the 10.13 box from outside, and do:

rbb-osx1013-3:~ buildbot$ ioreg -n IODisplayWrangler | grep -i IOPowerManagement
      | |   "IOPowerManagement" = {"DevicePowerState"=1,"CapabilityFlags"=0,"CurrentPowerState"=1,"MaxPowerState"=4}

Sure enough, it's in power state 1, which I guess is sleep.

To verify I used caffeinate properly:

rbb-osx1013-3:~ buildbot$ ps augxw | grep caffein
buildbot          378   0.0  0.1  4340580   5292 s005  S+    4:15PM   0:00.01 caffeinate -d -t 31536000 -s -t 31536000 -u -t 31536000 -i -t 31536000 sh bslave.sh run

To see what assertions are being held:

rbb-osx1013-3:~ buildbot$ pmset -g assertionslog
2017-11-20 19:34:27 -0800 : Showing all currently held IOKit power assertions
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             1
   ExternalMedia                  0
   PreventUserIdleSystemSleep     1
   NetworkClientActive            1
Listed by owning process:
   pid 378(caffeinate): [0x0000002a000180c2] 03:19:21 PreventUserIdleSystemSleep named: "caffeinate command-line tool" 
	Details: caffeinate asserting on behalf of 'sh' (pid 377)
	Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
	Timeout will fire in 31524038 secs Action=TimeoutActionRelease
   pid 378(caffeinate): [0x0000002a000580c3] 03:19:21 PreventUserIdleDisplaySleep named: "caffeinate command-line tool" 
	Details: caffeinate asserting on behalf of 'sh' (pid 377)
	Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
	Timeout will fire in 31524038 secs Action=TimeoutActionRelease
   pid 378(caffeinate): [0x0000002a000780c4] 03:19:21 PreventSystemSleep named: "caffeinate command-line tool" 
	Details: caffeinate asserting on behalf of 'sh' (pid 377)
	Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
	Timeout will fire in 31524038 secs Action=TimeoutActionRelease
   pid 378(caffeinate): [0x0000002a000980c5] 03:19:21 UserIsActive named: "caffeinate command-line tool" 
	Details: caffeinate asserting on behalf of 'sh' (pid 377)
	Localized=THE CAFFEINATE TOOL IS PREVENTING SLEEP.
	Timeout will fire in 31524038 secs Action=TimeoutActionRelease
   pid 52(powerd): [0x00002e8700118318] 00:01:32 NetworkClientActive named: "com.apple.powermanagement.ttyassertion" 
Kernel Assertions: 0x104=USB,MAGICWAKE
   id=501  level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.1a200000 owner=USB Optical Mouse
   id=502  level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.1d100000 owner=Dell USB Entry Keyboard
   id=503  level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.3a200000 owner=Dell USB Entry Keyboard
   id=504  level=255 0x100=MAGICWAKE mod=12/31/69, 4:00 PM description=en0 owner=en0

Showing assertion changes(Press Ctrl-T to log all currently held assertions):

Looks like all the right assertions are active...?

So, what am I doing wrong?  Why is the display still sleeping?

**Comment by gautamkrishnar** [comment] 2018-01-10 07:47
Hi, I am having the same issue. Any update on this?

**Comment by barney89** [comment] 2018-01-26 16:15
Hi guys. Same issue. I have just downloaded the GitHub last version. I have installed the package but it doesn't run (Macbook Pro High Sierra 10.13.3)

**Comment by x74353** [comment] 2018-01-26 16:35
@barney89 @gautamkrishnar 

I still stand by this being an issue with macOS itself (or SMC). Try running the `caffeinate -d` command in Terminal to see if your Mac stays awake. If it doesn't, please [file a bug with Apple](https://developer.apple.com/bug-reporting/).

**Comment by newmarcel** [comment] 2018-12-23 17:08
I'm closing this because macOS Mojave has been around for a long time now and I haven't received any more reports of problems similar to this.

**Closed by newmarcel** 2018-12-23 17:08 UTC

**Comment by Justsoos** [comment] 2019-09-21 06:12
as this page, https://apple.stackexchange.com/questions/219885/use-caffeinate-to-prevent-sleep-on-lid-close-on-battery
```
'sudo pmset -b sleep 0; sudo pmset -b disablesleep 1'
```
```
'sudo pmset -b sleep 5; sudo pmset -b disablesleep 0'
```
works for High Sierra, so, KeepingYouAwake could add the function by that commands

**Comment by digitalowlnyc** [comment] 2021-03-06 05:53
I noticed sometimes Amphetamine would not let me enter sleep (if I started a session, the try icon immediately reverted and the session did not initiate). I finally realized that in the Preferences there is an option under **"Battery" called "End session if charge below X percent"**. This was causing the issue - by then enabling the "_Prompt me before ending session_" setting, it was much clearer what was going on that prevented it from working.
