### ISSUE TITLE
Time remaining is negative

### ISSUE THREAD

**Issue by cubuspl42** [newmarcel/KeepingYouAwake#68] opened 2016-11-16 14:59 UTC
Yesterday I activated KeepYouAwake for 5 hours. I've finished working before timeout. When I've logged in today, KeepYouAwake was active and showing something like "-19 hours remaining". Is it an expected behavior? I think that KYA should dactivate when it detects that scheduled timeout is in the past, whatever the reason is (user closed the lid, baterry run out, etc).

**Comment by alexandreleroux** [comment] 2016-11-17 00:09
Not an expected behavior in my opinion. A bug! :-)

**Comment by newmarcel** [comment] 2019-08-09 21:28
I'm closing this because I haven't been able to reproduce it.

Feel free to open a new issue when this happens again and provide some steps to reproduce. Thanks 👍

**Closed by newmarcel** 2019-08-09 21:28 UTC
Labels: bug
